version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: etl_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl_app:
    build: .
    container_name: etl_app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/etl_db
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data

volumes:
  postgres_data:
